[package]
name = "sidebyside"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.26.3"
clap = { version = "4.5.4", features = ["derive"] }
crossterm = "0.27"
env_logger = "0.11.3"
log = "0.4.21"
color-eyre = "0.6.3"
tui-textarea = "0.4.0"
